### PR TITLE
feat: use account-js for token verification

### PR DESCRIPTION
**Pull request by Akarshit**
This PR makes a BREAKING change.

Till now the plugin/api used Hydra/Identity for authentication and user management. This PR replaces those with account-js. So from now on the user won't have to run hydra and identity service and the authentication will be done through graphql APIs.
This means the forms to do these things would have to be added to the front-end.

## Breaking Changes
The new system introduces `account-js` to add a authorization token and also to get current user from that token.

### CODE REVIEW

**Review by MohanNarayana — APPROVED** [review]
Looks great!

**Comment by loan-laux** [comment]
I just wanted to thank @Akarshit for this change which I think will be huge for Reaction in terms of adoption. I've used this branch to implement login on [our Next Commerce provider for MOC](https://github.com/vercel/commerce/pull/293), and what a bliss it was to use as a developer!

**Review by spencern — CHANGES_REQUESTED** [review]
Package.json should stay at version `0.0.0-development`

**Comment by Akarshit** [comment]
Updated the PR to keep the old version.

**Review by spencern — APPROVED** [review]
Thanks! Looks good.  [This review is specifically about the version numbers]

**Comment by Akarshit** [comment]
@MohanNarayana Added the password dependency to package.json. This is ready for review.

**Pull request merged**
